version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - translation-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: translation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - translation-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: translation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - translation-network

  redis:
    image: redis:alpine
    container_name: translation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - translation-network
    volumes:
      - redisdata:/data

networks:
  translation-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local 